config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    put '/users/edit',  to: 'users/registrations#update', as: :user_edit
  end
  resources :books, only: %i[index show]
end

app/views/partials/_flash_message.haml
%div.text-center
  - flash.each do |type, message|
    %div{'class': "alert alert-#{type == 'alert' || type == 'danger' ? 'danger' : 'success'}"}
      %a{'href': "#", 'class': "close", 'data-dismiss': "alert", 'aria-label': "close"} &times
      = message

app/views/partials/_footer.haml
%footer.navbar-inverse
    .container
        .row
            .col-sm-9
                %ul.list-inline.general-align.mb-25
                    %li
                        = link_to t('.home'), root_path, class: 'nav-link'
                    %li
                        = link_to t('.shop'), books_path, class: 'nav-link'
                    %li
                        %a.nav-link{href: "#"}= t('.orders')
                    %li
                        = link_to t('.settings'), user_session_path, class: 'nav-link'
            .col-sm-3
                %p.general-nav-mail= t('.email')
                %p.general-nav-number= t('.phone_number')
                %ul.list-inline.general-align
                    %li
                        %a.nav-link{href: "#"}
                            %i.fa.fa-facebook{'aria-hidden': "true"}
                    %li
                        %a.nav-link{href: "#"}
                            %i.fa.fa-twitter{'aria-hidden': "true"}
                    %li
                        %a.nav-link{href: "#"}
                            %i.fa.fa-google-plus{'aria-hidden': "true"}
                    %li
                        %a.nav-link{href: "#"}
                            %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/partials/_head.haml
%head
  %meta{charset: "UTF-8"}
  %meta{name: "viewport", content: "width=device-width"}
  %title= t('.title')
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_pack_tag 'application'
  = javascript_pack_tag 'application'

app/views/partials/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand= t('.title') 
      %a.shop-link.pull-right.visible-xs{href: "#"}
        %span.shop-icon
          %span.shop-quantity 3
    %a.shop-link.pull-right.hidden-xs{href: "#"}
      %span.shop-icon
        %span.shop-quantity 3
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to t('.home'), root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= t('.shop')
            %ul.dropdown-menu
              - categories.each do |category|
                %li
                  = link_to books_path(category_id: category.id) do
                    = category.title
            %li
              - if user_signed_in?
                %a.dropdown-toggle#user-email{ href: '#', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false' }
                  = current_user.email
                %ul.dropdown-menu
                  %li
                    = link_to t('.settings'), edit_user_registration_path
                  %li
                    = link_to t('.menu_order')
                  %li
                    = link_to t('.log_out'), destroy_user_session_path, method: :delete
              - else
                %li
                  = link_to t('.log_in'), new_user_session_path, class: 'collapse-link', id: 'log_in_link'
                %li
                  = link_to t('.sign_up'), new_user_registration_path, class: 'collapse-link', id: 'sign_up_link'